<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Select options_attachment-woocommerce_t_0f4399</name>
   <tag></tag>
   <elementGuidId>aa3ab64e-2ce7-408a-85d9-656ea0516c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-5881.status-publish.instock.product_cat-mudha-chairs.has-post-thumbnail.taxable.shipping-taxable.purchasable.product-type-variable > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>10e6487b-7447-414a-b5dc-7af0846faadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>67f03e90-cd44-4ec4-a38a-5feb8983fd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>92f36bef-8d2c-4394-9723-621d80f4a148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/MUDHA-115Large-324x324.jpeg?v=1701777920</value>
      <webElementGuid>2e232f76-4b36-4cba-8945-e54eb485a20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>b95b74ca-f48d-472e-940a-821e24f68fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>85ce6301-1d6e-47e5-a262-408306da5623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/MUDHA-115Large-324x324.jpeg?v=1701777920 324w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-115Large-150x150.jpeg?v=1701777920 150w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-115Large-100x100.jpeg?v=1701777920 100w</value>
      <webElementGuid>e69feed6-2203-408b-8c1d-d888d411b099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>ab2f3a98-0f5f-41e8-aee2-09ae4497885c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-5881 status-publish instock product_cat-mudha-chairs has-post-thumbnail taxable shipping-taxable purchasable product-type-variable&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>912e0e53-1315-4816-91df-c403bfbc0f69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/img</value>
      <webElementGuid>eb976def-b03a-43ac-b3f7-d52543820043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/MUDHA-115Large-324x324.jpeg?v=1701777920')]</value>
      <webElementGuid>f5b384d2-7645-4d32-9fca-2c8032190b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>33d1cc80-96c6-4c87-bb85-7d8660507a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/MUDHA-115Large-324x324.jpeg?v=1701777920']</value>
      <webElementGuid>956d9cf0-b1b7-483c-a249-a499303d9e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
