<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to cart_attachment-woocommerce_thum_569712</name>
   <tag></tag>
   <elementGuidId>18f46c6a-894c-472c-bf4f-5f7577c1fb29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-6154.status-publish.instock.product_cat-iron-stools-frame.has-post-thumbnail.taxable.shipping-taxable.purchasable.product-type-variable > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cefa15e0-2620-4eb3-87c5-576f2eaaca86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>2d165aab-74f8-4d80-b7db-3c84023009f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>3538fb8c-e61b-4943-87a0-0fef6c239efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-324x324.jpeg?v=1701777785</value>
      <webElementGuid>d60ff121-6ad1-47aa-9d74-831cd58074c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>61c9b21e-716f-4d28-9697-78ef0f7a74bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8976eb2c-a6bc-4f5b-9513-134ea07afe2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-324x324.jpeg?v=1701777785 324w, https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-300x300.jpeg?v=1701777785 300w, https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-150x150.jpeg?v=1701777785 150w, https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-768x768.jpeg?v=1701777785 768w, https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-416x416.jpeg?v=1701777785 416w, https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-100x100.jpeg?v=1701777785 100w, https://craferia.com/wp-content/uploads/2023/08/Mudha-130C.jpeg?v=1701777785 960w</value>
      <webElementGuid>d1957c61-4959-4f7a-8a85-b4457303d945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>0befd25a-4ad2-44cc-bd21-f8785a24d40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-6154 status-publish instock product_cat-iron-stools-frame has-post-thumbnail taxable shipping-taxable purchasable product-type-variable&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>666bd434-4c41-4e73-a8fc-8304fe2c985b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/img</value>
      <webElementGuid>b6834390-966b-4296-9730-bc8b6eb3bdf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-324x324.jpeg?v=1701777785')]</value>
      <webElementGuid>cf8458f9-6daf-4220-b48e-52e75bf8a818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>d44e354c-3303-4f9e-b0bd-ee296954b3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/Mudha-130C-324x324.jpeg?v=1701777785']</value>
      <webElementGuid>6b324707-3df9-4a2d-9f0a-15321954a4e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
