<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pinterest</name>
   <tag></tag>
   <elementGuidId>1ac76047-a3a1-4528-8b2e-dfb952dea30f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-15']/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.wp-social-link.wp-social-link-pinterest.wp-block-social-link > a.wp-block-social-link-anchor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e03a1a4c-1768-4165-bc6b-c0b5db538a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value> noopener nofollow</value>
      <webElementGuid>54ee2b19-9218-4b76-998d-b1c7e508e4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ca063f09-ffa2-43b0-8888-fb66e13bee2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://in.pinterest.com/craferia/?eq=craferia&amp;etslf=7970</value>
      <webElementGuid>2c1750ec-ff6c-4d44-b63c-9dd4b356ad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-social-link-anchor</value>
      <webElementGuid>56b5e22f-a14b-447a-949c-cb91f16c66e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pinterest</value>
      <webElementGuid>b5848812-eaea-4dfa-b32d-603e240cedcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-15&quot;)/ul[@class=&quot;wp-block-social-links has-visible-labels is-layout-flex wp-block-social-links-is-layout-flex&quot;]/li[@class=&quot;wp-social-link wp-social-link-pinterest  wp-block-social-link&quot;]/a[@class=&quot;wp-block-social-link-anchor&quot;]</value>
      <webElementGuid>261964e4-0c84-4075-acde-f85b9e1f4869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-15']/ul/li[5]/a</value>
      <webElementGuid>72d14e3d-a13f-4889-b540-3c5471d33592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/following::a[1]</value>
      <webElementGuid>1181d01a-3a3b-4b24-a94a-82804ef60c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::a[2]</value>
      <webElementGuid>9671b83e-0e13-4a54-973c-5b3ddc55cf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://in.pinterest.com/craferia/?eq=craferia&amp;etslf=7970')]</value>
      <webElementGuid>78e865fe-fdfe-4c4a-a688-e8eba50a2ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/ul/li[5]/a</value>
      <webElementGuid>77d69470-86a8-4980-b679-0c66c279819f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://in.pinterest.com/craferia/?eq=craferia&amp;etslf=7970' and (text() = 'Pinterest' or . = 'Pinterest')]</value>
      <webElementGuid>6abbe0ea-e32a-45b6-b9ea-11c47ddedec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
