<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Google</name>
   <tag></tag>
   <elementGuidId>7b985823-e102-4e64-bd80-ba1921e8f543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-15']/ul/li[4]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.wp-social-link.wp-social-link-google.wp-block-social-link > a.wp-block-social-link-anchor > span.wp-block-social-link-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b310249e-fd16-46f8-993c-e00afa4ac281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-social-link-label</value>
      <webElementGuid>d68cc04e-67cc-4d0a-90a8-cf69f4fae72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>c7cf207a-c02a-442b-b4ed-937d6d5a84b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-15&quot;)/ul[@class=&quot;wp-block-social-links has-visible-labels is-layout-flex wp-block-social-links-is-layout-flex&quot;]/li[@class=&quot;wp-social-link wp-social-link-google  wp-block-social-link&quot;]/a[@class=&quot;wp-block-social-link-anchor&quot;]/span[@class=&quot;wp-block-social-link-label&quot;]</value>
      <webElementGuid>cbf62347-79aa-4d80-b053-39fc132d0c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-15']/ul/li[4]/a/span</value>
      <webElementGuid>64e83ccf-8a7d-4800-9c8b-04d2fd52511d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::span[1]</value>
      <webElementGuid>6c20a855-23ea-484a-bf16-6a209e808e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::span[2]</value>
      <webElementGuid>31c05fcf-30aa-4dfe-90d7-8b730fb42657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinterest'])[1]/preceding::span[1]</value>
      <webElementGuid>9a60f665-7bc0-490e-81c0-01aae02b6eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Google']/parent::*</value>
      <webElementGuid>5abcd1e5-906e-475d-8dff-63d9514f7766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>c6878ccd-d48b-4426-94ed-ad7ce29c1472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Google' or . = 'Google')]</value>
      <webElementGuid>a5bff81f-6856-4d8e-abc6-391d1292f5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
