<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Instagram</name>
   <tag></tag>
   <elementGuidId>7e402fb0-97fd-4952-8872-28915e64257f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-15']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.wp-social-link.wp-social-link-instagram.wp-block-social-link > a.wp-block-social-link-anchor > span.wp-block-social-link-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25fe9ee6-020f-4dea-8b82-920c523d5deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-social-link-label</value>
      <webElementGuid>196e3aff-2bcc-4c88-8dd3-b21fd3b564f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instagram</value>
      <webElementGuid>54549dc2-11c4-4780-833e-5caa588b74ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-15&quot;)/ul[@class=&quot;wp-block-social-links has-visible-labels is-layout-flex wp-block-social-links-is-layout-flex&quot;]/li[@class=&quot;wp-social-link wp-social-link-instagram  wp-block-social-link&quot;]/a[@class=&quot;wp-block-social-link-anchor&quot;]/span[@class=&quot;wp-block-social-link-label&quot;]</value>
      <webElementGuid>892dad57-a248-44ca-8c32-a0e02f7beb73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-15']/ul/li[2]/a/span</value>
      <webElementGuid>41c072b8-e642-4f40-8eab-d085f8a07a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::span[1]</value>
      <webElementGuid>524141e6-f8c0-4a37-b155-42f6d4fb639f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow us'])[1]/following::span[2]</value>
      <webElementGuid>e37b7f07-5f74-4a12-9aca-c680716eb4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/preceding::span[1]</value>
      <webElementGuid>5781e1e6-cca8-421d-b9ae-c4daf883f1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/preceding::span[2]</value>
      <webElementGuid>ebf57dce-f00c-4f9d-84f2-e9cf5053502f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instagram']/parent::*</value>
      <webElementGuid>2851b521-9653-41b2-986a-f64f3ca007d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>4fa1d67a-1246-42e5-8201-ce8d7b7ad078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Instagram' or . = 'Instagram')]</value>
      <webElementGuid>a29e104b-995d-4a32-9d11-f758e68fd7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
