<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fd670ae8-a04e-42d1-aaa0-00525b6d8125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Collectibles&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e44eea45-a70a-4d2b-ae84-a3c9a9e08046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/09/Collectibles_img.png?v=1701777604</value>
      <webElementGuid>3a40ff41-6f77-4812-9f25-72666d83bb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Collectibles</value>
      <webElementGuid>dd5aebc7-3e9b-4e99-ada0-28c71b11ee8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>b0e02eee-f10f-4311-b668-af3868e3d091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>981406a3-77b0-4928-87af-9b0818e1b65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product-category product first&quot;]/a[1]/img[1]</value>
      <webElementGuid>9f704964-7242-4717-959c-9ace3591189e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li/a/img</value>
      <webElementGuid>79ab8211-89d3-4ca7-9e19-c742aea9ee5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Collectibles']</value>
      <webElementGuid>b2f25ed6-d1a6-4fc8-9eea-50535f5f1ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>799bf52b-2c18-4978-b313-da61e4b86686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/09/Collectibles_img.png?v=1701777604' and @alt = 'Collectibles']</value>
      <webElementGuid>df6c7253-1884-4285-bde1-683e3dc8299c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
