<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1,197.50 599.00</name>
   <tag></tag>
   <elementGuidId>f11ca187-8641-49a8-aa4d-2f548b76d42b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-4352.status-publish.instock.product_cat-diffuser-burner.has-post-thumbnail.sale.taxable.shipping-taxable.purchasable.product-type-variable > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > span.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b19a8a8-6d17-43ac-911b-b2a7a33e932c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>2ea919e9-d975-4a22-9001-589f11fb3eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹1,197.50 ₹599.00</value>
      <webElementGuid>4b126f28-06a6-4b12-bc41-90202db2689b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-4352 status-publish instock product_cat-diffuser-burner has-post-thumbnail sale taxable shipping-taxable purchasable product-type-variable&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/span[@class=&quot;price&quot;]</value>
      <webElementGuid>6a28369d-ba7a-4be8-ac18-ef932e180a26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/span</value>
      <webElementGuid>5aa3c57a-7260-4543-866c-f660791f057a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elegant Ceramic Diffuser With Aroma essence Set'])[1]/following::span[1]</value>
      <webElementGuid>4437bdff-9e17-455c-9112-a60cc9daa0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALE'])[2]/following::span[1]</value>
      <webElementGuid>ccdc7722-5cc6-4e9c-8087-aeb552282387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>628b7ff4-28ae-4bb5-b8c4-214d51bba85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '₹1,197.50 ₹599.00' or . = '₹1,197.50 ₹599.00')]</value>
      <webElementGuid>30502e99-e2ed-4c53-a2cc-51219edf2de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
