<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to cart_attachment-woocommerce_thum_569712</name>
   <tag></tag>
   <elementGuidId>8ff9cf06-b404-42ab-942e-e28ba7d9106a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-5558.status-publish.instock.product_cat-bamboo-laundry-organizer-baskets.product_cat-bamboo-storage-basket-and-utility-baskets.product_cat-natural-mudha.has-post-thumbnail.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ffdb0a9-2994-4725-947b-aa2168377a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>2c05fcc1-d008-4cb8-aa7c-0527030268a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>2456ada2-3b31-4a15-824c-4b94099bc574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/23d1968a-bb34-45e0-9cfd-c74e5ae5cf1c-324x324.jpg?v=1704357742</value>
      <webElementGuid>4e237ed8-7132-4b08-bbae-89b04d7e2797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>3ab9c6ae-32a5-4212-9e01-62d66b001de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ebe68b38-7816-4920-926e-96e8d216710c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/23d1968a-bb34-45e0-9cfd-c74e5ae5cf1c-324x324.jpg?v=1704357742 324w, https://craferia.com/wp-content/uploads/2024/01/23d1968a-bb34-45e0-9cfd-c74e5ae5cf1c-150x150.jpg?v=1704357742 150w, https://craferia.com/wp-content/uploads/2024/01/23d1968a-bb34-45e0-9cfd-c74e5ae5cf1c-100x100.jpg?v=1704357742 100w</value>
      <webElementGuid>d0032136-afbb-48c4-afd3-51de2d5592fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>2468c5cf-f729-4b87-8945-703f87e910c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-5558 status-publish instock product_cat-bamboo-laundry-organizer-baskets product_cat-bamboo-storage-basket-and-utility-baskets product_cat-natural-mudha has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>abb38050-557d-48fd-97fc-b839e9f261c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/img</value>
      <webElementGuid>e53f611c-fa0b-4127-b05f-07bc9dd5b662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2024/01/23d1968a-bb34-45e0-9cfd-c74e5ae5cf1c-324x324.jpg?v=1704357742')]</value>
      <webElementGuid>00669a2f-e4b8-4f18-9a9a-79aadc1cf112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>189e0ba8-4be0-4ca3-b1c6-45d0c4da9e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2024/01/23d1968a-bb34-45e0-9cfd-c74e5ae5cf1c-324x324.jpg?v=1704357742']</value>
      <webElementGuid>999afec9-be2f-47dc-84ad-940b4fa0be11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
