<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Combo Bags</name>
   <tag></tag>
   <elementGuidId>81b6df6c-8bd6-4322-9108-bbdd541a9059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26722']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26722 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90d65d82-a458-4a5b-bb77-d25ae16102bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/combo-bags/</value>
      <webElementGuid>248e7d75-d459-43b6-a2d0-e01791d0fd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Combo Bags</value>
      <webElementGuid>557ef88c-9c70-4b63-93ff-90f4e2ee9042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26722&quot;)/a[1]</value>
      <webElementGuid>467661ae-1ff5-46dd-a86f-b7b7e84a6969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26722']/a</value>
      <webElementGuid>c29fa721-8e09-4411-b483-3347473930c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Combo Bags')]</value>
      <webElementGuid>d4724c89-8a57-4908-ac0a-e80acf278174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clutches'])[1]/following::a[1]</value>
      <webElementGuid>c0b10ee7-c9c9-4c84-baa8-ffac4fd35093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sling bags'])[1]/following::a[2]</value>
      <webElementGuid>745e531d-79e7-44c9-a22c-2f8cefa1ef38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mobile pouch / potli bag'])[1]/preceding::a[1]</value>
      <webElementGuid>7a931bb4-3ff8-4fae-a386-ae95040e6901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Under 500'])[1]/preceding::a[2]</value>
      <webElementGuid>fb958849-dbf0-47eb-a2dc-b9f89307852d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Combo Bags']/parent::*</value>
      <webElementGuid>ce76421a-baae-49eb-ad80-c6b4922534ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/combo-bags/')]</value>
      <webElementGuid>d97e360a-e59c-45d1-bcad-ea723006d4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[5]/a</value>
      <webElementGuid>26987b99-14bf-4cc3-a4e5-59660fa37928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/combo-bags/' and (text() = 'Combo Bags' or . = 'Combo Bags')]</value>
      <webElementGuid>1b9d01b8-f905-461d-8942-a5a0c5891f6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
