<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_clutches</name>
   <tag></tag>
   <elementGuidId>13cd28d6-1112-45fb-a633-58d7257ff64f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26721']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26721 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba9cf6fb-0026-4da4-bf78-25bba6e17c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/clutches/</value>
      <webElementGuid>c28450a8-33c1-4fd7-9759-dda11b460617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>clutches</value>
      <webElementGuid>b449b7c8-7f0b-478e-83d3-46d095cd96eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26721&quot;)/a[1]</value>
      <webElementGuid>16fa0369-e2f1-42cc-9aea-1b5d73ab1518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26721']/a</value>
      <webElementGuid>1aecf8e3-08ef-4696-81a6-fa354200c859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'clutches')]</value>
      <webElementGuid>1aba041d-6b0e-42e0-9bac-55787f7f3128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sling bags'])[1]/following::a[1]</value>
      <webElementGuid>97f1caea-a1bd-4265-aae3-023373d5a270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shoulder bags'])[1]/following::a[2]</value>
      <webElementGuid>8c328b13-28a8-4b27-ba1c-624ffea072c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combo Bags'])[1]/preceding::a[1]</value>
      <webElementGuid>be3695ca-5a7f-410b-9bad-44397beca668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mobile pouch / potli bag'])[1]/preceding::a[2]</value>
      <webElementGuid>28a98032-13b1-4376-8a21-b57296eb666c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='clutches']/parent::*</value>
      <webElementGuid>80f2beae-ba9f-44f3-8354-9c4900920da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/clutches/')]</value>
      <webElementGuid>17e78a6e-9fd6-46cb-97d0-36763515ed77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[4]/a</value>
      <webElementGuid>aefb4587-01dc-43df-9c8f-fcd61a81ecde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/clutches/' and (text() = 'clutches' or . = 'clutches')]</value>
      <webElementGuid>36496b5b-421f-44f3-9b68-9cfe5b8a1357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
