<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Combo Bags</name>
   <tag></tag>
   <elementGuidId>e98d936d-ae00-41e0-abea-07940dd1e45c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26722']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26722 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>56d23900-8599-4b33-a966-5024b23c9ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/combo-bags/</value>
      <webElementGuid>1ea29b55-a260-4e42-a851-9ec44b60b572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Combo Bags</value>
      <webElementGuid>26b67a6a-226e-4346-af59-5bec1a4339ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26722&quot;)/a[1]</value>
      <webElementGuid>d2d72ae9-3482-4e19-9f7a-688c54c1c69b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26722']/a</value>
      <webElementGuid>e71e929e-783f-46ae-a2e1-c66b82d5defa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Combo Bags')]</value>
      <webElementGuid>7c67389c-f7f7-4e99-9233-37c887b18c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clutches'])[1]/following::a[1]</value>
      <webElementGuid>fd1b9a7e-88a8-4f60-a714-99c91c51df20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sling bags'])[1]/following::a[2]</value>
      <webElementGuid>50f8950c-82c7-4d33-a503-9131d223c285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mobile pouch / potli bag'])[1]/preceding::a[1]</value>
      <webElementGuid>1369639a-00f5-4581-8060-455576d82530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Under 500'])[1]/preceding::a[2]</value>
      <webElementGuid>cf0ba2e9-203e-4260-9741-3afe3a8725bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Combo Bags']/parent::*</value>
      <webElementGuid>be360b30-078b-4785-832c-4c9d848a5540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/combo-bags/')]</value>
      <webElementGuid>7d52bbbc-14d9-4cfa-b74e-bb708aab0ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[5]/a</value>
      <webElementGuid>85ff9b6b-8244-40c6-b94c-9c6da946e9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/combo-bags/' and (text() = 'Combo Bags' or . = 'Combo Bags')]</value>
      <webElementGuid>e738f525-a015-4f3b-bf68-bd012b27084f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
