<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_handbags</name>
   <tag></tag>
   <elementGuidId>8cfe5c17-98cd-4993-8cba-f80d10e776f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26718']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26718 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36960886-de80-4c2c-8e09-27e1504db687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/handbags/</value>
      <webElementGuid>cfc819f1-e87c-44f4-a22a-df180228d4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>handbags</value>
      <webElementGuid>3bc9dc33-b258-471e-8a94-0f79e6e921a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26718&quot;)/a[1]</value>
      <webElementGuid>9b7257d8-5bcb-4d50-ad23-dcad27970ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26718']/a</value>
      <webElementGuid>e2f9d96b-7a6a-4ef6-8056-a83c94bdca94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'handbags')]</value>
      <webElementGuid>8125c8d9-62ce-4c21-99a6-f9bad4c7b248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ladies Bags'])[1]/following::a[1]</value>
      <webElementGuid>b82c0b0a-b018-4b6a-91b8-3bfea1442fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Storage Basket and Utility Baskets'])[1]/following::a[2]</value>
      <webElementGuid>ef4da740-8e4a-46e8-a128-3deef18effe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shoulder bags'])[1]/preceding::a[1]</value>
      <webElementGuid>36fcbf26-d7b2-467a-b6b5-8a73a8f74f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sling bags'])[1]/preceding::a[2]</value>
      <webElementGuid>d040dbbf-ae6a-41f7-a5f7-412d2fd973aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='handbags']/parent::*</value>
      <webElementGuid>3f8c5b8c-ca34-4301-a6b4-f890a43768c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/handbags/')]</value>
      <webElementGuid>3d64a055-986d-42d2-ac96-5df4d567a418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a</value>
      <webElementGuid>a338ce74-a840-4862-a913-3f98b794f07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/handbags/' and (text() = 'handbags' or . = 'handbags')]</value>
      <webElementGuid>cd23657d-025d-4d97-a8fb-de0de0105e2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
