<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mobile pouch  potli bag</name>
   <tag></tag>
   <elementGuidId>ad5fa50e-9a26-4aac-97e5-4b52dc106e34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26723']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26723 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>595ae3e6-e299-45ec-a571-d18541fa81eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/mobile-pouch-potli-bag/</value>
      <webElementGuid>4d7e1b24-96f6-426f-ab91-e9a51e4b8eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mobile pouch / potli bag</value>
      <webElementGuid>594132c3-0d0c-4749-a39b-431338acf7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26723&quot;)/a[1]</value>
      <webElementGuid>8a8e6f8b-edbc-4cbf-952b-8dbcf6411f0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26723']/a</value>
      <webElementGuid>51d49400-705e-4186-81b4-a5938b758c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mobile pouch / potli bag')]</value>
      <webElementGuid>facb6655-e23b-4d4e-b110-2819ac8636fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combo Bags'])[1]/following::a[1]</value>
      <webElementGuid>878c64b4-91d5-47b7-a937-a979d3f89400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clutches'])[1]/following::a[2]</value>
      <webElementGuid>38974287-7943-4a96-95f1-8f2b9e072f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Under 500'])[1]/preceding::a[1]</value>
      <webElementGuid>c9c803dd-4291-4488-a017-f8938879072b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Decor – Items &amp; Gifts'])[2]/preceding::a[2]</value>
      <webElementGuid>29b63373-508a-4790-a3e6-6b93ed0d996d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mobile pouch / potli bag']/parent::*</value>
      <webElementGuid>1687e714-0abf-422f-bf0d-938023133746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/mobile-pouch-potli-bag/')]</value>
      <webElementGuid>89e1e53a-965c-40f0-85c2-8359ecac7057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[6]/a</value>
      <webElementGuid>6823dc3a-0b40-4f48-876f-c96f4ed19257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/mobile-pouch-potli-bag/' and (text() = 'mobile pouch / potli bag' or . = 'mobile pouch / potli bag')]</value>
      <webElementGuid>5efb2d1b-0a07-405c-b22b-308212d1f376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
