<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sling bags</name>
   <tag></tag>
   <elementGuidId>c679e131-02dc-4b61-a42b-0c402f22b9b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26720']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26720 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c21483b-7e36-4267-961d-8e0531548cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/sling-bags/</value>
      <webElementGuid>0b1b5a9d-36d3-466e-a9f0-5a4186e050f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sling bags</value>
      <webElementGuid>1aa5d077-5776-4d17-a271-bf547b01d090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26720&quot;)/a[1]</value>
      <webElementGuid>5cd8d44d-9793-45b1-98bc-a3dd935871d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26720']/a</value>
      <webElementGuid>82ce173a-0af1-400a-9c5a-45c229b1f8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sling bags')]</value>
      <webElementGuid>22a23845-f2ff-400f-819f-e87a561467e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shoulder bags'])[1]/following::a[1]</value>
      <webElementGuid>b8001508-bd8f-4ae2-a156-fc8326080ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='handbags'])[1]/following::a[2]</value>
      <webElementGuid>00e8fcfb-b2cf-4719-8632-cb2da1014135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clutches'])[1]/preceding::a[1]</value>
      <webElementGuid>c73cbe3d-f235-4152-aaee-086b32c4ee26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combo Bags'])[1]/preceding::a[2]</value>
      <webElementGuid>bb62d99e-acf8-4fed-b878-c8620361bc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sling bags']/parent::*</value>
      <webElementGuid>4d2f7208-2b98-4d66-ab60-12d879fc324d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/sling-bags/')]</value>
      <webElementGuid>6b580d78-e028-4a57-9528-e93c57bc309a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[3]/a</value>
      <webElementGuid>c11eb516-4c4d-4cc0-b4c2-9422210943db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/sling-bags/' and (text() = 'Sling bags' or . = 'Sling bags')]</value>
      <webElementGuid>7d92968d-56ab-4dbf-ad02-730c24b537f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
