<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sling bags</name>
   <tag></tag>
   <elementGuidId>5334016a-ba01-423e-a5f7-1404dbecbf22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26720']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26720 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63ae675d-6161-488d-a3b1-57a3c225b252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/sling-bags/</value>
      <webElementGuid>82578bcb-a59a-4b7d-b469-982620ec9687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sling bags</value>
      <webElementGuid>1d698e7c-56a4-462e-8f94-c9204822652b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26720&quot;)/a[1]</value>
      <webElementGuid>ef17345f-012b-4262-92a9-d74e2955c00a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26720']/a</value>
      <webElementGuid>5d9cf70d-7229-49f6-9119-44a2fee0d38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sling bags')]</value>
      <webElementGuid>6621a39d-ba25-4b1b-ad69-735bef481c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shoulder bags'])[1]/following::a[1]</value>
      <webElementGuid>4629639f-801f-43aa-b7e3-0b74d278cce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='handbags'])[1]/following::a[2]</value>
      <webElementGuid>3cdf62a3-972a-4105-a9f1-7548a255bf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clutches'])[1]/preceding::a[1]</value>
      <webElementGuid>1f56a135-6e12-47bf-be44-f84340a77092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combo Bags'])[1]/preceding::a[2]</value>
      <webElementGuid>dc7e9938-0328-40ad-949f-1e280d7b4edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sling bags']/parent::*</value>
      <webElementGuid>21e8e959-e6d4-4308-a577-2fb9f3816f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/sling-bags/')]</value>
      <webElementGuid>93830279-b40f-429d-b446-1c5c62b0f3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[3]/a</value>
      <webElementGuid>58818ff8-c8c2-4720-98e8-9a4fa5610fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/sling-bags/' and (text() = 'Sling bags' or . = 'Sling bags')]</value>
      <webElementGuid>2c4b95a2-eb11-481a-9d79-e3d243a60b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
