<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to cart_attachment-woocommerce_thum_569712_1</name>
   <tag></tag>
   <elementGuidId>33f19c91-0757-4df0-a6b5-a753ed5d38c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-27508.status-publish.instock.product_cat-home-decor.product_cat-key-holders.product_cat-wall-panels.has-post-thumbnail.sale.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1d84a9b4-792d-41a6-80ab-f7792952376c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>d6b6de54-3304-4aad-ad61-e9d6dc282261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>2d883958-2111-49d9-8374-636478850d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/HD-742B-324x324.jpeg?v=1704353214</value>
      <webElementGuid>1aa1485e-8860-46c7-b226-4697a82bde8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>5a83bebc-97d4-45bb-99a1-87c654257e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>9d037d59-7db6-405a-8a28-145c98233d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/HD-742B-324x324.jpeg?v=1704353214 324w, https://craferia.com/wp-content/uploads/2024/01/HD-742B-150x150.jpeg?v=1704353214 150w, https://craferia.com/wp-content/uploads/2024/01/HD-742B-100x100.jpeg?v=1704353214 100w</value>
      <webElementGuid>704b1f5f-372f-4ddb-947c-e19ed1482d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>3c6c6e7f-1a9f-4efe-991a-bb44fd077e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-27508 status-publish instock product_cat-home-decor product_cat-key-holders product_cat-wall-panels has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>ad94402f-9b72-41ca-8dbd-0de1f8102552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[3]/a/img</value>
      <webElementGuid>196e663f-e2ed-4a9d-aa13-aecbd246f8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2024/01/HD-742B-324x324.jpeg?v=1704353214')]</value>
      <webElementGuid>c7195f60-1099-4ae0-a651-5ea08ae24687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>80ae787f-6c06-4c9f-9219-8899cb7b9b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2024/01/HD-742B-324x324.jpeg?v=1704353214']</value>
      <webElementGuid>9d3f1c36-d00f-42f0-b5ed-b0d8192d7471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
