<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Bamboo has become an increasingly popular_0c0f68</name>
   <tag></tag>
   <elementGuidId>415eaa62-51d1-495a-8853-dac3d76511fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.term-description > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9b201c3d-1b9e-4658-9ab4-bab82c8d3986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo has become an increasingly popular choice for furniture and home decor due to its sustainability, durability and aesthetic appeal. One example of this is bamboo shelves and racks, which serve as both practical storage solutions and attractive pieces of decor.</value>
      <webElementGuid>4c262cfa-e577-4720-823f-2784b8efd116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;term-description&quot;]/p[1]</value>
      <webElementGuid>e2bb51ac-66fd-4bcd-8a40-dd2ac936c0b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/p</value>
      <webElementGuid>ea7d7d7e-39a7-41d2-aebe-a6afdacdc258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Shelf / Rack'])[3]/following::p[1]</value>
      <webElementGuid>4fde26ed-d335-4d06-8a91-3903f1cb2e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[3]/following::p[1]</value>
      <webElementGuid>eaece825-b7d1-4682-80dc-2b5b893feb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/p</value>
      <webElementGuid>3c740d4a-00d9-4c55-80a7-aa3c3d9facbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Bamboo has become an increasingly popular choice for furniture and home decor due to its sustainability, durability and aesthetic appeal. One example of this is bamboo shelves and racks, which serve as both practical storage solutions and attractive pieces of decor.' or . = 'Bamboo has become an increasingly popular choice for furniture and home decor due to its sustainability, durability and aesthetic appeal. One example of this is bamboo shelves and racks, which serve as both practical storage solutions and attractive pieces of decor.')]</value>
      <webElementGuid>096a4d98-82f9-4fd1-95a7-ed6028d37724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
