<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Double Tapestry</name>
   <tag></tag>
   <elementGuidId>3b2340a7-0856-45bc-b49c-cde75382cc22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26728']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26728 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88983915-7f4c-423a-8e97-0fd0e260bdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/double-tapestry/</value>
      <webElementGuid>0ef96bf8-32b2-45e6-9d93-99bc82cd3e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Double Tapestry</value>
      <webElementGuid>62bd851e-ec40-48ff-9178-9250ab93308e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26728&quot;)/a[1]</value>
      <webElementGuid>7f016220-c8b4-4fb9-a275-edc312b0cc51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26728']/a</value>
      <webElementGuid>50234515-bcfc-463f-97e5-fde85f929ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Double Tapestry')]</value>
      <webElementGuid>db999141-78f3-4023-83cc-8caa663cbf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round Tapestry'])[1]/following::a[1]</value>
      <webElementGuid>fc3723aa-650b-45c3-a8db-98d11586ee56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Tapestry'])[1]/following::a[2]</value>
      <webElementGuid>14351e9b-794e-4d36-a05c-2cf0a0b952ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Storage Basket and Utility Baskets'])[1]/preceding::a[1]</value>
      <webElementGuid>3704ccba-36f4-432b-a8ab-7f650ef3a42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ladies Bags'])[1]/preceding::a[2]</value>
      <webElementGuid>29194072-91b8-413c-bba3-fe626fbc433d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Double Tapestry']/parent::*</value>
      <webElementGuid>18ea411a-a904-4681-8472-03393260b6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/double-tapestry/')]</value>
      <webElementGuid>8ac1c643-2172-4a0a-ab97-177f3e3aa69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[3]/a</value>
      <webElementGuid>02c55aa6-cc30-4ec8-b0d7-aab48a2a2712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/double-tapestry/' and (text() = 'Double Tapestry' or . = 'Double Tapestry')]</value>
      <webElementGuid>e59c4961-6a14-4d74-94d9-5c2fdf680a26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
