<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Round Tapestry</name>
   <tag></tag>
   <elementGuidId>34d759fe-d485-4ec6-bd3d-e4befab0493a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26727']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26727 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca0553b4-bc50-4011-b429-11cd9c67d6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/round-tapestry/</value>
      <webElementGuid>d202071e-ad3e-4fda-a188-85c856c87f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Round Tapestry</value>
      <webElementGuid>42c50ed9-d7b9-49b0-939e-7a7fcd3b220c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26727&quot;)/a[1]</value>
      <webElementGuid>702ffe2d-fe3c-4dfd-a101-5a2998911709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26727']/a</value>
      <webElementGuid>25a42064-e356-4438-a5e5-5c278063f975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Round Tapestry')]</value>
      <webElementGuid>9529a326-2268-441e-a25c-b13abc13eff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Tapestry'])[1]/following::a[1]</value>
      <webElementGuid>7e2396ed-c076-4211-98f1-05851a9421de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tapestry'])[1]/following::a[2]</value>
      <webElementGuid>32f8522a-bb2c-452a-851d-fb99c39571f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Tapestry'])[1]/preceding::a[1]</value>
      <webElementGuid>fd460b8c-a52c-4a52-9b0a-2a45bbe854f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Storage Basket and Utility Baskets'])[1]/preceding::a[2]</value>
      <webElementGuid>0f1958e9-4b2d-4bec-95bc-bd7c3a17e1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Round Tapestry']/parent::*</value>
      <webElementGuid>3e2c7ca1-9a21-4c82-b459-902742f6d6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/round-tapestry/')]</value>
      <webElementGuid>c846046a-569c-405c-ab22-2c3ad40b966f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/a</value>
      <webElementGuid>c4b5d1a3-5bbb-4f01-9f1f-caa7de0541b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/round-tapestry/' and (text() = 'Round Tapestry' or . = 'Round Tapestry')]</value>
      <webElementGuid>e787736a-ac0f-4f6f-9048-6647191569d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
