<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Single Tapestry</name>
   <tag></tag>
   <elementGuidId>c077a641-c790-41ed-853f-c76d2e3875c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26726']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26726 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dd7fa5c-4329-4405-9488-9ebc55107dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/single-tapestry/</value>
      <webElementGuid>20623a0d-2e50-4f6a-951d-46346ce0ccaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single Tapestry</value>
      <webElementGuid>5c529b43-ec57-4434-a56d-dfa7551ad3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26726&quot;)/a[1]</value>
      <webElementGuid>2a4479c3-d56f-45d2-a253-39210995bc09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26726']/a</value>
      <webElementGuid>018467bd-0b92-4318-9187-e1f4e05bf51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Single Tapestry')]</value>
      <webElementGuid>62c8046a-bae9-494d-94bd-daabc2c5e1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tapestry'])[1]/following::a[1]</value>
      <webElementGuid>03f72f45-8a18-4e8a-88bd-2e9c59815448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blankets &amp; Quilts'])[1]/following::a[2]</value>
      <webElementGuid>9f80977d-028c-48c0-85ac-ff8113b41b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round Tapestry'])[1]/preceding::a[1]</value>
      <webElementGuid>6e00a8a8-a137-4a49-ab56-3ca93bb016e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Tapestry'])[1]/preceding::a[2]</value>
      <webElementGuid>bc6323ab-d8ba-4764-a0c3-569a02b36846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single Tapestry']/parent::*</value>
      <webElementGuid>1ea44448-a18a-4029-a522-237ddaa7a5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/single-tapestry/')]</value>
      <webElementGuid>2870ebb9-9e6c-44f2-a344-e33fb019dc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>f414db24-6411-4001-891b-a1e32091eec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/single-tapestry/' and (text() = 'Single Tapestry' or . = 'Single Tapestry')]</value>
      <webElementGuid>796c9021-b5a6-4ee5-a68d-268516fc7f3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
