<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tapestry</name>
   <tag></tag>
   <elementGuidId>d48bd005-67e1-463a-8286-ea54c55e1838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26725']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26725 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d285b4ca-7f41-4468-83dd-4db472ac9460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/tapestry/</value>
      <webElementGuid>583cedf0-6178-4e91-b412-7949097a1a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>28139b0a-b075-40a7-8bae-364ddcd49a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tapestry</value>
      <webElementGuid>b945d9e7-41cd-4fb7-bfc2-f836188be944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26725&quot;)/a[1]</value>
      <webElementGuid>d70abd47-5993-46db-8ed5-f18581e0f212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26725']/a</value>
      <webElementGuid>ef69f6d6-927e-424b-b2f6-88bc48e1349a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tapestry')]</value>
      <webElementGuid>3f40e627-7268-4c34-a00f-a2ad71c7eb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blankets &amp; Quilts'])[1]/following::a[1]</value>
      <webElementGuid>094f98f1-c46e-49ff-97c2-1cdb56d7f28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Bedsheet'])[1]/following::a[2]</value>
      <webElementGuid>1dac527c-b3b1-4391-91a2-7dddf1eab2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Tapestry'])[1]/preceding::a[1]</value>
      <webElementGuid>8fb6a9a9-8292-4d5a-98d6-2d9288c380b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round Tapestry'])[1]/preceding::a[2]</value>
      <webElementGuid>a30cb578-de0b-47eb-83e1-ce35b9b11efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tapestry']/parent::*</value>
      <webElementGuid>6d60a027-837d-4b57-9046-8fadbc7bf9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/tapestry/')]</value>
      <webElementGuid>723bbd26-2f3c-4551-8c2e-987fe0a9e6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[5]/a</value>
      <webElementGuid>8604cf13-2920-4c8f-8d7a-5c6ec1c29002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/tapestry/' and (text() = 'Tapestry' or . = 'Tapestry')]</value>
      <webElementGuid>5e07b83e-7b0e-4afd-a405-e5e7dba23930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
