<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Furnishings</name>
   <tag></tag>
   <elementGuidId>8b02bffb-143c-4b6f-9053-43d29af87671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26709']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26709 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f1d0346-0253-46fb-bd3c-09fd6da067e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/furnishings/</value>
      <webElementGuid>dbfde791-f844-4576-9814-922c5b4de135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Furnishings</value>
      <webElementGuid>32dfbd2c-8b85-4764-980a-5da28dc50963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26709&quot;)/a[1]</value>
      <webElementGuid>66e4598a-2b97-4d3f-a1fb-0f8353d7dd9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26709']/a</value>
      <webElementGuid>4a548683-fd16-44ae-8f05-ffad2de8200d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Furnishings')]</value>
      <webElementGuid>44944d9a-e56e-4f80-ab71-b87975f6a65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha Table'])[1]/following::a[1]</value>
      <webElementGuid>de6c500f-7313-47ad-a2ea-5c74758db55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha chairs'])[1]/following::a[2]</value>
      <webElementGuid>312ba429-9f81-491c-b946-803ff41bee78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cushions'])[1]/preceding::a[1]</value>
      <webElementGuid>0dfe95f9-8077-4383-9ef2-1cfd8a8428ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placemats &amp; Runners'])[1]/preceding::a[2]</value>
      <webElementGuid>7d553184-9c39-4c6a-a400-c253d22e1b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Furnishings']/parent::*</value>
      <webElementGuid>7166df95-7a9d-4290-ad74-e667bc369ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/furnishings/')]</value>
      <webElementGuid>24ea5098-76d6-4775-b34d-df0b9921771d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>db5f279b-2ca0-465a-bfc6-e84bab283a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/furnishings/' and (text() = 'Furnishings' or . = 'Furnishings')]</value>
      <webElementGuid>b4bc7c9a-7a26-4476-a075-838d30c9e3d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
