<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hotel  Restaurant Furniture</name>
   <tag></tag>
   <elementGuidId>189aa9e2-e2b7-4432-8040-f799e90ab330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26701']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26701 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65a1b5f0-6e19-434d-a1cc-ec75d61c3186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/hotel-restaurant-furniture/</value>
      <webElementGuid>9d1883ba-afbe-4cef-a233-60b9e1c53246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotel &amp; Restaurant Furniture</value>
      <webElementGuid>55598fd5-11d1-49cc-b695-938b00726f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26701&quot;)/a[1]</value>
      <webElementGuid>f904193b-c2b1-41dc-8d31-6f2e1f61da86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26701']/a</value>
      <webElementGuid>cf8bf704-1240-4a7f-8260-4e7b4ae6a5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hotel &amp; Restaurant Furniture')]</value>
      <webElementGuid>a6e74f57-79fa-4d4d-9aa3-e54877171809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outdoor Furniture'])[1]/following::a[1]</value>
      <webElementGuid>0dbd3e74-9b55-40a1-b085-4e72f7cc914c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cane Furniture'])[1]/following::a[2]</value>
      <webElementGuid>220f2c8b-236f-4910-a47a-8be0356ac6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha'])[1]/preceding::a[1]</value>
      <webElementGuid>9fa8461d-fba7-4617-95c7-84e3dbb93557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha Stools'])[1]/preceding::a[2]</value>
      <webElementGuid>7e8baac9-1605-40df-971b-ecfbb623dc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotel &amp; Restaurant Furniture']/parent::*</value>
      <webElementGuid>50f79d21-b2a3-4ca0-9d11-bd05143177d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/hotel-restaurant-furniture/')]</value>
      <webElementGuid>3b16ee43-947d-482e-a17d-1ad5393004f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>a8eb757c-8070-4f2e-9f02-c6ad06d6f6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/hotel-restaurant-furniture/' and (text() = 'Hotel &amp; Restaurant Furniture' or . = 'Hotel &amp; Restaurant Furniture')]</value>
      <webElementGuid>bad79f02-5db4-48a4-95cf-fa8e68febab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
