<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clock</name>
   <tag></tag>
   <elementGuidId>21475f79-0256-4a76-ae0e-c2cf5a83870c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26695']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26695 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6318ba26-d279-4600-8de1-28ecb32c1038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/clock/</value>
      <webElementGuid>73605766-e467-420a-9b7a-f399230d4160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clock</value>
      <webElementGuid>3e861f51-9332-4a9e-84f9-b3a84b23da3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26695&quot;)/a[1]</value>
      <webElementGuid>d83e05d4-47b6-4c06-b2cb-b811ab99b695</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26695']/a</value>
      <webElementGuid>d65e4452-2e69-4218-b51c-3cce8d412157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clock')]</value>
      <webElementGuid>76b0ffbc-053a-4d2c-a75a-8555fc1734bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lamps &amp; Lightings'])[1]/following::a[1]</value>
      <webElementGuid>6332733b-bce4-4dc0-b1dd-a6fe2bb2cb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diffuser / Burner'])[1]/following::a[2]</value>
      <webElementGuid>60068d68-d0c1-4364-b393-ba11488bdd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key Holders'])[1]/preceding::a[1]</value>
      <webElementGuid>ad5cf2c7-de7c-442a-b50a-522be71d9a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handmade Furnitures'])[1]/preceding::a[2]</value>
      <webElementGuid>8c6e4bf7-1362-4974-8b1f-1f76011c5d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clock']/parent::*</value>
      <webElementGuid>d8e2648d-7448-4a2b-a8c4-fe012f6ce8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/clock/')]</value>
      <webElementGuid>45290611-2b68-4020-8bee-ab91fe3abfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[5]/a</value>
      <webElementGuid>416819db-4264-4472-b3d0-202d1b3757b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/clock/' and (text() = 'Clock' or . = 'Clock')]</value>
      <webElementGuid>193680f1-8d48-4d56-9efc-436486e09144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
