<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shoulder bags</name>
   <tag></tag>
   <elementGuidId>86f1261e-ad40-4d99-ab75-ef259c2c96dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26719']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26719 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6dd10d39-f459-49d0-904b-c86d3df51109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/shoulder-bags/</value>
      <webElementGuid>53bab9a2-b782-4c66-bd99-51c1857ddacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shoulder bags</value>
      <webElementGuid>2dfb8e57-2937-49e6-9c31-0ee879fc0266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26719&quot;)/a[1]</value>
      <webElementGuid>326480c6-d4df-46cd-b1ae-f6b2d55d8cec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26719']/a</value>
      <webElementGuid>6cf7e420-ae84-48a0-addf-62a74e3c8c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shoulder bags')]</value>
      <webElementGuid>11bc3578-66ba-47d6-8f82-498e978d71a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='handbags'])[1]/following::a[1]</value>
      <webElementGuid>58a2f1e6-38a8-4e27-90ed-ee02177b3cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ladies Bags'])[1]/following::a[2]</value>
      <webElementGuid>f8879992-126c-484c-b1ad-3ba1b9d20fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sling bags'])[1]/preceding::a[1]</value>
      <webElementGuid>958848b2-be6e-4798-9c2b-109fba584cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clutches'])[1]/preceding::a[2]</value>
      <webElementGuid>1b128d75-9bc6-4cac-b882-a641635ebf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shoulder bags']/parent::*</value>
      <webElementGuid>3f926ec6-d2fb-4a4a-8422-74b60ee9a617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/shoulder-bags/')]</value>
      <webElementGuid>d9c23213-6454-422e-829e-a6809b07fa42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[2]/a</value>
      <webElementGuid>32dcbc0f-3d32-43d9-bb13-848f4770ea75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/shoulder-bags/' and (text() = 'Shoulder bags' or . = 'Shoulder bags')]</value>
      <webElementGuid>60167115-02cc-4bef-8736-c28e86e54c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
