<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Key Holders</name>
   <tag></tag>
   <elementGuidId>b6fd08aa-4115-4667-a082-94b7523ea812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26696']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26696 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00290ce8-52c7-451c-a1c6-73bf7a4339b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/key-holders/</value>
      <webElementGuid>1b56a522-5dad-47fb-9f55-c14b1e0edee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Key Holders</value>
      <webElementGuid>415719be-40c3-4751-b8c5-5e85bbb9cc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26696&quot;)/a[1]</value>
      <webElementGuid>369705e2-fb01-4bca-bac1-8fc9fbc7ec47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26696']/a</value>
      <webElementGuid>7627b0fa-28d3-405c-b4e0-476de49ab1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Key Holders')]</value>
      <webElementGuid>6a733c41-b40c-43a9-99bb-1c85a1b511de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clock'])[1]/following::a[1]</value>
      <webElementGuid>7d1a9509-c3b9-46e6-b763-da2c5282c5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lamps &amp; Lightings'])[1]/following::a[2]</value>
      <webElementGuid>a9a44647-1e18-4bec-a1c6-380bac456082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handmade Furnitures'])[1]/preceding::a[1]</value>
      <webElementGuid>918c1a02-c47e-46a0-8e35-6dea68424b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Furniture'])[1]/preceding::a[2]</value>
      <webElementGuid>cc00da2d-e0a1-4add-9bbe-9d582eb154df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Key Holders']/parent::*</value>
      <webElementGuid>a0d06da1-c0a1-4eef-8c70-b3332d82ab82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/key-holders/')]</value>
      <webElementGuid>0ae28f76-be36-4763-84d2-3ee8af31311b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[6]/a</value>
      <webElementGuid>601d12e1-23c5-41b9-8914-5a4911e8da86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/key-holders/' and (text() = 'Key Holders' or . = 'Key Holders')]</value>
      <webElementGuid>33d579a8-f7ce-434c-a9cc-2c808ec779da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
