<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lamps  Lightings</name>
   <tag></tag>
   <elementGuidId>89008860-d23a-40b5-8093-cdba3db49b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26694']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26694 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3366bc61-1dd6-4db3-a6be-4372f15f11e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/lamps-lightings/</value>
      <webElementGuid>0738d205-6970-481c-9cf3-bbd40ea9ce5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lamps &amp; Lightings</value>
      <webElementGuid>883e6b7f-91ba-4344-9a6a-8c75c424d8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26694&quot;)/a[1]</value>
      <webElementGuid>ed305c9a-cb3a-4741-aaed-fe425768d75a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26694']/a</value>
      <webElementGuid>3a80d660-8a89-45db-b19b-f1fac896eae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lamps &amp; Lightings')]</value>
      <webElementGuid>b483dff1-ff75-4fe0-b951-2f8fc83dc55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diffuser / Burner'])[1]/following::a[1]</value>
      <webElementGuid>f26f9dc0-428c-48b5-aaf6-61e530d57fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo frame'])[1]/following::a[2]</value>
      <webElementGuid>d824d3ca-3efa-41ef-95e5-05d2a6a719ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clock'])[1]/preceding::a[1]</value>
      <webElementGuid>215e6790-4ab3-45ba-8c1c-1e5ec82a54d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key Holders'])[1]/preceding::a[2]</value>
      <webElementGuid>efb25c8d-9a21-4aba-b081-149b382f4f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lamps &amp; Lightings']/parent::*</value>
      <webElementGuid>252ef3dd-d868-4c21-990c-0dd834b0b178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/lamps-lightings/')]</value>
      <webElementGuid>6b4a3f13-7cdd-40a1-8314-62b83230ff72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/a</value>
      <webElementGuid>a6fdc77c-7d75-438f-bee9-4953d6611177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/lamps-lightings/' and (text() = 'Lamps &amp; Lightings' or . = 'Lamps &amp; Lightings')]</value>
      <webElementGuid>57ba60d2-fbc0-44ce-ba36-10012bd688a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
