<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__category_banner_image</name>
   <tag></tag>
   <elementGuidId>c5233189-c139-4a85-9a85-85e9c57250ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.category_banner_image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b1981ce-42fa-4639-ace4-79f87c2d1a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg</value>
      <webElementGuid>1d8bc53c-22cf-42e6-b7bb-3489981496d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category_banner_image</value>
      <webElementGuid>e8c570e5-62ce-4d75-beb9-d1cd9b002062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;col-full&quot;]/div[@class=&quot;wbm_banner_image banner&quot;]/img[@class=&quot;category_banner_image&quot;]</value>
      <webElementGuid>d074b773-d0a0-429e-a3b5-88b0e9b8fbec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/img</value>
      <webElementGuid>23985bf1-2962-4af8-b76c-6b173bd8db92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg')]</value>
      <webElementGuid>91c7b312-75ef-4d41-b1c6-ba7facec2d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>9cf03c71-3a3c-461a-b70f-ad02076ddb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg']</value>
      <webElementGuid>b219049f-0201-40f2-8232-4b41bb4b09b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
