<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Laundry  Organizer Baskets</name>
   <tag></tag>
   <elementGuidId>f0d64177-5b59-4627-bb1d-34192c6e68f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26666']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26666 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7065490-6408-4160-9135-0006d48d06c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-laundry-organizer-baskets/</value>
      <webElementGuid>1f922a4a-5cef-4acd-a143-e373e57703ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Laundry &amp; Organizer Baskets</value>
      <webElementGuid>ff1a114a-7b60-445e-a697-8c20a11c1c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26666&quot;)/a[1]</value>
      <webElementGuid>c88d14af-3c76-4d8c-99d1-025290fe2ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26666']/a</value>
      <webElementGuid>0b5843e5-3f54-4ff6-b9bf-9ac8022f3cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Laundry &amp; Organizer Baskets')]</value>
      <webElementGuid>32424ba0-e65a-4cb8-b5d8-d956a5aa4bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Shelf / Rack'])[1]/following::a[1]</value>
      <webElementGuid>15f9af0c-140d-4b69-8cf2-8713da1e1773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Tables'])[1]/following::a[2]</value>
      <webElementGuid>dcbd2456-7e15-46ec-aa3a-81174284a4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Natural Mudha'])[1]/preceding::a[1]</value>
      <webElementGuid>fb4fd999-74c4-4577-8fa8-e561fd05712a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pidha stools'])[1]/preceding::a[2]</value>
      <webElementGuid>26f68528-1267-462a-8675-1fa5a63fb8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bamboo Laundry &amp; Organizer Baskets']/parent::*</value>
      <webElementGuid>1cb52946-13d9-4379-94d5-d8540480b1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-laundry-organizer-baskets/')]</value>
      <webElementGuid>2dc6e2ed-6c84-47d8-aba9-12d68bad4add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>e4ec9c27-6555-4061-bcba-c38153b85e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-laundry-organizer-baskets/' and (text() = 'Bamboo Laundry &amp; Organizer Baskets' or . = 'Bamboo Laundry &amp; Organizer Baskets')]</value>
      <webElementGuid>d9ef5710-44a2-49c2-b15c-caec431509f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
