<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pidha stools</name>
   <tag></tag>
   <elementGuidId>a10b241c-fcaf-40a2-866f-81a0d7e2378a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26670']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26670 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d17a243f-04aa-4ffc-a665-1dad734cc5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/pidha-stools/</value>
      <webElementGuid>e8362e12-9d9a-4b13-b04f-276fe3a1f173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pidha stools</value>
      <webElementGuid>7761b8f3-80f7-427e-a4ab-7405743923ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26670&quot;)/a[1]</value>
      <webElementGuid>454d3053-fe8a-4483-9b0a-8553f6cc2a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26670']/a</value>
      <webElementGuid>01e4ff4b-06d1-40a3-b999-86d03a0d845d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pidha stools')]</value>
      <webElementGuid>dcad332e-841f-41fd-8108-c7607fe65f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Natural Mudha'])[1]/following::a[1]</value>
      <webElementGuid>672d901a-6777-4009-93f2-885ee44e53f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bamboo Laundry &amp; Organizer Baskets'])[1]/following::a[2]</value>
      <webElementGuid>af235d74-79eb-4fec-b2ee-a8195f003f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iron Stools Frame'])[1]/preceding::a[1]</value>
      <webElementGuid>21b33928-06c0-4e12-9016-7317c32d4a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cane Baskets'])[1]/preceding::a[2]</value>
      <webElementGuid>31efc3d0-0ae4-4b9c-b515-cceb105dcbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pidha stools']/parent::*</value>
      <webElementGuid>a6e66edd-33b1-4e29-8700-b9cbb6d1d111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/pidha-stools/')]</value>
      <webElementGuid>a1247fa1-97d3-4512-b290-0c909af84fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>e30f2a5f-7321-4200-be67-7f22524e8e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/pidha-stools/' and (text() = 'Pidha stools' or . = 'Pidha stools')]</value>
      <webElementGuid>d2c72811-6ee8-40a1-8e9e-15d3a1af60cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
