<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wooden Furnitures</name>
   <tag></tag>
   <elementGuidId>babd402c-925e-4854-876a-dfb8e03049dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26675']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26675 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>955e1112-e7dd-4fd8-945e-329c3e31c4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/wooden-furnitures/</value>
      <webElementGuid>79e6cbb5-5561-4845-8362-f3c692a8297e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wooden Furnitures</value>
      <webElementGuid>6eb1cd10-c931-4504-955c-488593c56375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26675&quot;)/a[1]</value>
      <webElementGuid>0fe79338-0cad-4155-9408-14b226eaca24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26675']/a</value>
      <webElementGuid>e8c1da01-cd14-4d5a-8cb6-a938e7308644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wooden Furnitures')]</value>
      <webElementGuid>e1534c3e-8279-46a2-8159-9de1412f5b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sofa chair / Long chair'])[1]/following::a[1]</value>
      <webElementGuid>da78a72d-6e63-44dd-8e42-411219f1fd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cane Baskets'])[1]/following::a[2]</value>
      <webElementGuid>e32d981f-337a-422f-9c6b-21390227fda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cane Furniture'])[1]/preceding::a[1]</value>
      <webElementGuid>28532a1a-4cce-4eed-9291-40096e24e740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outdoor Furniture'])[1]/preceding::a[2]</value>
      <webElementGuid>d12592e8-ec7c-4b05-8137-f18f4231f9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wooden Furnitures']/parent::*</value>
      <webElementGuid>312150da-c9c0-41db-aaec-7e2091f28d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/wooden-furnitures/')]</value>
      <webElementGuid>22e49bec-1f21-42af-98ed-697af485e246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[8]/a</value>
      <webElementGuid>287e5ca3-f722-4c5a-9321-7ae30a2550ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/wooden-furnitures/' and (text() = 'Wooden Furnitures' or . = 'Wooden Furnitures')]</value>
      <webElementGuid>5bf9ecbc-cdca-4082-b1c0-571e055c18ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
