<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to cart_attachment-woocommerce_thum_569712</name>
   <tag></tag>
   <elementGuidId>d2904b93-19dd-43d7-b4fe-75c6fa983084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-28187.status-publish.instock.product_cat-outdoor-furniture.has-post-thumbnail.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fbb3b619-eb15-492c-9409-20c5a72fe5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>178af66a-c680-4d09-9f72-87c0a447b0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>cb0645e5-adee-4af8-8b43-fa9afb3d3743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/12/WhatsApp-Image-2023-12-27-at-11.49.16-AM-324x324.jpeg?v=1703671294</value>
      <webElementGuid>626d9f35-5c7d-4d1f-855b-d90b02dc1fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>feedf0e7-5e0f-499e-95ee-8822346d8b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6e70258c-6df9-4296-9414-49275906ea0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/12/WhatsApp-Image-2023-12-27-at-11.49.16-AM-324x324.jpeg?v=1703671294 324w, https://craferia.com/wp-content/uploads/2023/12/WhatsApp-Image-2023-12-27-at-11.49.16-AM-150x150.jpeg?v=1703671294 150w, https://craferia.com/wp-content/uploads/2023/12/WhatsApp-Image-2023-12-27-at-11.49.16-AM-100x100.jpeg?v=1703671294 100w</value>
      <webElementGuid>b50c2c25-8ba0-4a19-a1b9-b83ce02f659c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>c123e1bc-ba79-478e-8d92-b57d18f12e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-28187 status-publish instock product_cat-outdoor-furniture has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>c964e637-d004-476c-b5b9-f991ebcf95c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/img</value>
      <webElementGuid>30eb3584-5d89-4344-b0ca-bd5d22930594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/12/WhatsApp-Image-2023-12-27-at-11.49.16-AM-324x324.jpeg?v=1703671294')]</value>
      <webElementGuid>ee987408-6650-402c-aa9f-b72e9a8a5c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>21a56dc5-6b58-403b-a699-7168d1fa3bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/12/WhatsApp-Image-2023-12-27-at-11.49.16-AM-324x324.jpeg?v=1703671294']</value>
      <webElementGuid>933c7b84-dff1-4a9c-92d2-fa76b4bc4abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
