<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mudha</name>
   <tag></tag>
   <elementGuidId>084fa172-592b-49c8-8719-49d8f0f50b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26704']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26704 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18b9d42e-6616-486f-893a-44f537cb18e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/mudha/</value>
      <webElementGuid>7a55ea39-5c74-430c-bd41-66e5cad7cc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mudha</value>
      <webElementGuid>2673fcb9-fc6d-458c-9f49-590f12f66311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26704&quot;)/a[1]</value>
      <webElementGuid>b12e0df5-f7fc-438c-bf7d-b424185dbd8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26704']/a</value>
      <webElementGuid>d0c8f2b7-cec4-4383-bb36-bfa9f0e8251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Mudha')])[3]</value>
      <webElementGuid>5c126184-973c-4a24-91b2-7362ad8aca40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel &amp; Restaurant Furniture'])[1]/following::a[1]</value>
      <webElementGuid>4abdae48-0e0b-4b2c-ab02-2c8757e20c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outdoor Furniture'])[1]/following::a[2]</value>
      <webElementGuid>956cc09e-60e4-4f2e-91f7-af12c2905b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha Stools'])[1]/preceding::a[1]</value>
      <webElementGuid>2fee7444-9fb6-4495-9252-40376dc30a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha chairs'])[1]/preceding::a[2]</value>
      <webElementGuid>ee6b776d-7d27-4592-91fa-d300e514d73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mudha']/parent::*</value>
      <webElementGuid>a4b24d7f-9237-4d14-8aac-fb84d1a8e7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/mudha/')]</value>
      <webElementGuid>4668acbf-34bc-40c2-af91-1843cea93d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>6a613a98-ccc4-4896-932b-4489c48bbfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/mudha/' and (text() = 'Mudha' or . = 'Mudha')]</value>
      <webElementGuid>b4933f2e-72c4-4f37-ae70-ff583e12e004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
