<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Outdoor Furniture</name>
   <tag></tag>
   <elementGuidId>1848e358-7bc7-477d-98ff-6564cba4b731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26702']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26702 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7e95744-308d-4496-969b-3aed6952eca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/outdoor-furniture/</value>
      <webElementGuid>5332db15-b58f-4323-b11a-883bb53efa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outdoor Furniture</value>
      <webElementGuid>dd1bae65-2d56-4c01-bed8-e5be23c2b838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26702&quot;)/a[1]</value>
      <webElementGuid>bef2a002-e240-4a1e-86ba-45e905b8e51e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26702']/a</value>
      <webElementGuid>eb853457-b3b2-4ef6-b6d8-41fa38a07c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Outdoor Furniture')]</value>
      <webElementGuid>e81ab291-fd2c-4bf0-9faa-42fee7592a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cane Furniture'])[1]/following::a[1]</value>
      <webElementGuid>2fef6854-35fe-44db-badd-dff4066ad8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wooden Furnitures'])[1]/following::a[2]</value>
      <webElementGuid>7bb3be67-9b64-40d1-88b6-27e176e37765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel &amp; Restaurant Furniture'])[1]/preceding::a[1]</value>
      <webElementGuid>4a8fce61-e853-4548-9e4a-07f3cadfdf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha'])[1]/preceding::a[2]</value>
      <webElementGuid>a70aef09-13a7-48b1-bc9f-aae994a1646d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outdoor Furniture']/parent::*</value>
      <webElementGuid>9169d77d-914b-4d54-bd2d-cb3c360e895d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/outdoor-furniture/')]</value>
      <webElementGuid>ceb33be6-fa43-46f3-8433-fb18372aa019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>6b0701c5-a909-45d2-9d22-1abb2ef51774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/outdoor-furniture/' and (text() = 'Outdoor Furniture' or . = 'Outdoor Furniture')]</value>
      <webElementGuid>50ca193d-b2c1-4abe-b911-cf17d14edbd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
