<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to cart_attachment-woocommerce_thum_569712</name>
   <tag></tag>
   <elementGuidId>6b134a18-5027-47f6-9150-92921ca95141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-6159.status-publish.instock.product_cat-clock.product_cat-showpieces-figurines.product_cat-table-organizer.has-post-thumbnail.sale.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a40ce76f-62a2-4c60-b6fa-4ef16afd9538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>27d84f39-cb03-4d1d-ac27-e91be1f702bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>d73869c7-f347-4837-a94f-a4a49cff42e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/HD-714D-324x324.webp</value>
      <webElementGuid>66f1f5f1-7bd9-4b49-bf4e-67ec92a29f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>dde109a2-7d20-4f4b-bf68-8d77e4dc219b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>e99f8351-8a92-4945-b8b4-ad2b25945f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/HD-714D-324x324.webp 324w, https://craferia.com/wp-content/uploads/2023/08/HD-714D-100x100.webp 100w, https://craferia.com/wp-content/uploads/2023/08/HD-714D-416x416.webp 416w, https://craferia.com/wp-content/uploads/2023/08/HD-714D-300x300.webp 300w, https://craferia.com/wp-content/uploads/2023/08/HD-714D-150x150.webp 150w, https://craferia.com/wp-content/uploads/2023/08/HD-714D-768x768.webp 768w, https://craferia.com/wp-content/uploads/2023/08/HD-714D.webp 960w</value>
      <webElementGuid>65f3ee0e-c1d8-430d-a8a5-407f678ab7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>51798b39-e18d-45a3-a59c-d6b06ee0e29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-6159 status-publish instock product_cat-clock product_cat-showpieces-figurines product_cat-table-organizer has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>d01534bb-2458-47a9-a7e8-a483e433b2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/img</value>
      <webElementGuid>6cc0b422-0e1f-4c4a-af57-2071b12752c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/HD-714D-324x324.webp')]</value>
      <webElementGuid>548e8534-c5f3-4566-95b5-25fe1e8ac64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>3366e9cd-7106-4d96-b360-3e2ad36055fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/HD-714D-324x324.webp']</value>
      <webElementGuid>81825e54-e3bb-4ea7-b40b-b56d4beb0fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
