<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_4,679.50 2,340.00</name>
   <tag></tag>
   <elementGuidId>bdc89c49-756d-44ce-9bf2-c7b022937b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-6159.status-publish.instock.product_cat-clock.product_cat-showpieces-figurines.product_cat-table-organizer.has-post-thumbnail.sale.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > span.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0678fe5c-283e-499a-9e33-8f3b6fe4f367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>6e804eaa-838b-40da-88f6-aee1e7186657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹4,679.50 ₹2,340.00</value>
      <webElementGuid>7c6e2ce2-a178-4775-a39e-591280d2519a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-6159 status-publish instock product_cat-clock product_cat-showpieces-figurines product_cat-table-organizer has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/span[@class=&quot;price&quot;]</value>
      <webElementGuid>d3967ca5-d65c-4b1a-88a4-8c0a1fd8e2c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/span</value>
      <webElementGuid>b0240684-b6fb-4443-b869-676df2c62852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stylish Hand Painted Helicopter Wall Clock with Contemporary Design showpiece home decor'])[1]/following::span[1]</value>
      <webElementGuid>34d2c400-bbf5-4c7b-b0b9-e5dc6b985d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALE'])[2]/following::span[1]</value>
      <webElementGuid>77e81864-96c0-4d66-a011-3442c2fde5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>e012278b-7c21-4edb-9a9c-5b62188fb0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '₹4,679.50 ₹2,340.00' or . = '₹4,679.50 ₹2,340.00')]</value>
      <webElementGuid>98f97156-f46f-46d6-bdc2-35d144118f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[3]/a/span</value>
      <webElementGuid>1736c43a-1820-4c46-aeb9-6d6c57dff1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antique Metal Cycle Wall Clock handicrafts showpiece'])[1]/following::span[1]</value>
      <webElementGuid>e4199929-3359-48e4-b489-25f8b8a5b9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALE'])[3]/following::span[1]</value>
      <webElementGuid>d3e69f04-6b3b-4977-ab33-0beff0cb9448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>9bf929e7-e6b1-4818-9606-cf6700c1dbec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
