<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search for_s</name>
   <tag></tag>
   <elementGuidId>2081298b-2ea5-414a-9940-8007a120b458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='woocommerce-product-search-field-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#woocommerce-product-search-field-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5af1cf2c-390f-42d6-a9c1-a855d160ea1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>cc979591-fc85-44ff-a987-ebc35e25d8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>woocommerce-product-search-field-0</value>
      <webElementGuid>b5573f11-0bec-4827-8c2f-765e1afb66a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>60d7b28f-45da-4bdb-81b1-ec743a3834c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search products…</value>
      <webElementGuid>10d5f50d-b80e-4709-9bef-b13933c5e1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>3ff2d638-c5c7-4b3c-b5a5-f5ef5c96c83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;woocommerce-product-search-field-0&quot;)</value>
      <webElementGuid>7d9799b9-f718-464d-bb11-d31b8482ce04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='woocommerce-product-search-field-0']</value>
      <webElementGuid>00cbafa8-5cd2-401a-b702-eaf12d95ad62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='masthead']/div/div[2]/div/form/input</value>
      <webElementGuid>a9c8db56-a09f-41e6-8d73-376d369cd879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>030615e4-acbe-43e7-a90d-ed7fe4d68a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'woocommerce-product-search-field-0' and @placeholder = 'Search products…' and @name = 's']</value>
      <webElementGuid>9aaecac0-9a24-4942-91fb-5f58973c7b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
