<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mobile pouch  potli bag</name>
   <tag></tag>
   <elementGuidId>3d5aa190-4c14-4fb8-a6c1-d14c18bb1859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26723']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26723 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3502a82-9110-4d59-aa6e-7495b1f2589e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/mobile-pouch-potli-bag/</value>
      <webElementGuid>342e7396-f664-4b2a-beb8-c70192dfdf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mobile pouch / potli bag</value>
      <webElementGuid>67d39954-12e3-4ba3-8fab-9ae9277609c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26723&quot;)/a[1]</value>
      <webElementGuid>ef711aac-bd1d-4cb3-8f4a-837b42b16e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26723']/a</value>
      <webElementGuid>59e19ef4-29b7-4c78-b3de-e3cfd6406677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mobile pouch / potli bag')]</value>
      <webElementGuid>5b320298-81a4-40fe-a380-e4d45a69b126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combo Bags'])[1]/following::a[1]</value>
      <webElementGuid>a84d5ec3-dbd8-49e8-b92e-0f48a40b2e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clutches'])[1]/following::a[2]</value>
      <webElementGuid>222b13e8-7a09-4042-a5a0-31503d837da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Under 500'])[1]/preceding::a[1]</value>
      <webElementGuid>5a34f180-31e2-4506-8782-c3c6c23757fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Decor – Items &amp; Gifts'])[2]/preceding::a[2]</value>
      <webElementGuid>d97ed12d-dbab-4df3-b851-56914bf4a163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mobile pouch / potli bag']/parent::*</value>
      <webElementGuid>903ca9cf-f16a-41c3-87d9-9aea92011e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/mobile-pouch-potli-bag/')]</value>
      <webElementGuid>5607cb15-9068-4027-a69a-b58dfa7f4cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[6]/a</value>
      <webElementGuid>f08d95f5-fd7d-4be4-a883-fedbfab0d0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/mobile-pouch-potli-bag/' and (text() = 'mobile pouch / potli bag' or . = 'mobile pouch / potli bag')]</value>
      <webElementGuid>736edba1-a57e-452a-b9ac-ae215b463326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
